name: test
on: push
jobs:
  build:
    name: Super Linter
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Run Super Linter
        uses: github/super-linter@v3
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  set-node:
    name: set up hexo
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      
      - name: run node
        uses: actions/setup-node@v2
        with:
          node-version: 15
      - name: set up hexo-cli
        run: |
          npm install hexo-cli -g
          npm install hexo
          echo 'PATH="$PATH:./node_modules/.bin"' >> ~/.profile
